export const ADD_FAVORITE = "ADD_FAVORITE";
export const REMOVE_FAVORITE = "REMOVE_FAVORITE";
export const ORDER_FAVORITES = "ORDER_FAVORITES";
export const FILTER_GENDER = "FILTER_GENDER";
export const FILTER_STATUS = "FILTER_STATUS";
